### ISSUE TITLE
Why Flutter dependency?

### ISSUE THREAD

**Issue by shinayser** [thelabs-dev/flutter_swapi#1]
Hello thanks for your library!

May I ask why it is a Flutter plugin since it only uses http requests?
Using the Flutter dependency makes this library unable to be used with pure dart projects (like on bakcend).

My suggestion is to remove the Flutter dependency and its related folders (android, ios, etc..) since they are useless for the library to work!

Best regards!

**Comment by fcrizul** [comment]
Hello, thanks for the suggestion, we already removed the unused dependency.

Thanks again.
Best regards

**Comment by shinayser** [comment]
Great job! I just noted that you forgot to update the project description here on github.
It stills saying that is for Flutter instead of Dart. 

Best regards!
